### ISSUE TITLE
Incorrect params handling is case of using 'translate-n' directive

### ISSUE THREAD

**Issue by ivan-zakharchuk** [Polyconseil/easygettext#16]
gettext-extract from Jade:

```
div(translate-n="$index+1", translate, translate-plural="{{someExpression1}}") Lorem ipsum
div {{someExpression2}}
```

produce incorrect values:

```
msgid "Lorem ipsum"
msgid_plural "{{someExpression2}}"
msgstr ""
```

and this is because of presence `translate-n` attr, which is actually required for defining when plural should be used(https://angular-gettext.rocketeer.be/dev-guide/annotate/)

**Comment by vperron** [comment]
Hmmm, interesting one. I'll have a look at how to fix it, unless you have an idea already ?

**Comment by ivanzvakoms** [comment]
actually it works in general case, and I see that this happening only in one place, so I'll try to investigate this and/or provide more info how this reproduce

**Comment by vperron** [comment]
Any news about this ?

**Comment by ivan-zakharchuk** [comment]
Sorry, I don't have time to work on this, please check if the issue is still the case and close if it doesn't repro anymore.

**Comment by vperron** [comment]
It seems fixed. Please reopen if this happens again.
