### ISSUE TITLE
recursive path support

### ISSUE THREAD

**Issue by codeskyblue** [Polyconseil/easygettext#18]
for example we got files

```
- foo
   |-- x.html
   `-- bar/
         |-- y.html
```

Can we simply use  `foo/**/*.html`

**Comment by vperron** [comment]
The thing is, `foo/**/*.html` is not POSIX. So you're for now, supposed to "feed" easygettext with a list of files you want to apply extraction to, that was the easiest thing for now :)

Passing this kind of arguments is possible though, it's just not implemented yet. Problem is, I'm lazy, so if that is a feature you need, let the magic of open source happen and come up with a tested/documented pull request, I'll happily merge it :)

**Comment by codeskyblue** [comment]
use find and grep for now

**Comment by vperron** [comment]
Yep, that's what we do. grep ? what for ?

**Comment by codeskyblue** [comment]
just cant work on Windows

**Comment by vperron** [comment]
well then, windows needs a find tool, right ? ;)

Actually, PowerShell and / or the `dir` command work in that case.

But again, if you're in need of this, please suggest a pull request :)

**Comment by codeskyblue** [comment]
Iam lazy too. use git-bash installed on windows to solve the problem

**Comment by escapedcat** [comment]
Is it right, that this works directly from the command line:
```
./node_modules/easygettext/dist/extract-cli.js --output ./dictionary.pot ./src/**/*.html
```
But it does not work from within `package.json` like this:
```
"scripts": {
  "translations:extract": "gettext-extract --output ./dictionary.pot ./src/**/*.html"
},
```
?

**Comment by vperron** [comment]
No, not like that INSIDE easygettext (because the `node_modules/.bin` can't contain the executables for, well, easygettext itself, there are only the dependecie's executables there)

But if you have an app that installs `easygettext` (for instance, as a devDependency) then, you'll be able to add this rule to your app's package.json.
