### ISSUE TITLE
How to set Chinese as the native language in gettext

### ISSUE THREAD

**Issue by sdwangbaotong** [Polyconseil/easygettext#23]
Well I didn't find any configuration to set the non-English language as native language, so after the po file generated, gettext take English as the default, so the msgstr in en.po is filled, but my native file zh-cn.po is empty.

I didn't find gettext repo on github, so open an issue here.

**Comment by vperron** [comment]
Hello !

Can you explain a little more about your issue and give an example of the files used and the commands you have run ?

This will help !

Thank you,

**Comment by sdwangbaotong** [comment]
thanks for your quick response. My mother language is Chinese, so the generated po file in zh-CN looks should be take zh-CN as default. 

msgstr in below is "" which should be same with the key. The reason should be the msginit of gettext take en as default, and I didn't find how to configure it. some docs said online that gettext will read the system language as default, and my is Chinese already so not sure the reason.

zh-CN.po
"POT-Creation-Date: 2017-11-13 10:57+0800\n"
"PO-Revision-Date: 2017-11-10 21:21+0800\n"
"Language: zh-CN\n"

#: src/scripts/template.string:46
msgid "这里是中文"
msgstr ""
# the msgstr should be same as msgid in zh-CN, which is expected.

below is the en.po file, the msgstr is automatically set.

"POT-Creation-Date: 2017-11-13 10:57+0800\n"
"PO-Revision-Date: 2017-11-10 21:21+0800\n"
"Language: en\n"

#: src/scripts/template.string:46
msgid "这里是中文"
msgstr "这里是中文"
# the msgstr should be empty string here

**Comment by vperron** [comment]
Hi I'm closing this as outdated.
