### ISSUE TITLE
Attributes param also matches tags

### ISSUE THREAD

**Issue by nkostadinov** [Polyconseil/easygettext#26]
Currently the attribute parameter cannot distinguish between tags and attributes. I have <v-translate> tags and <span v-translate> and they are both extracted when I provide param  --attribute v-translate

**Comment by vperron** [comment]
I'm not sure what you mean by that :)

Can you provide an example ?

All the best,

**Comment by vperron** [comment]
Closing as I can't reproduce the issue.
