### ISSUE TITLE
fs dependency marked as a Security Holding Package

### ISSUE THREAD

**Issue by bulv1ne** [Polyconseil/easygettext#32]
What does the `fs` package do? On npm.org it looks like this is a [**Security holding package**](https://www.npmjs.com/package/fs). Is there a reason to have this as a dependency?

**Comment by vperron** [comment]
It has been fixed right now. I'll create a new release just for that. Thanks !

**Comment by bulv1ne** [comment]
Thanks yourself for the fast response :)
