### ISSUE TITLE
Question: extract `:label="$gettext('MY_STRING')"` possible?

### ISSUE THREAD

**Issue by escapedcat** [Polyconseil/easygettext#50]
I have following vue component:
```
<template>
      <special-input
        :label="$gettext('mylabel')"
      />
</template>
<script>
  ...
</script>
```

Is it possible to extract these strings with **easygettext** as well?  
At the moment I'm using [gettext-vue](https://github.com/GUI/gettext-vue) (which is using [xgettext-template](https://github.com/gmarty/xgettext) under the hood).

Not sure if this is or should be scope of this project. But now that it's handling `.vue` files pretty well already I would like to use it for all cases.

A work-around would be this:
```
<template>
      <special-input
        :label="mylabel"
      />
</template>
<script>
  ...
  computed: {
    mylabel() {
      return $gettext('MY_LABEL')
    },
  },
  ...
</script>
```

**Comment by vperron** [comment]
I'm pretty sure it could work, but this needs code. Please submit a PR !

**Comment by escapedcat** [comment]
Got ya. Let me see what I can do.

**Comment by escapedcat** [comment]
Had a look. It's a bit challenging for me.  
Would you implement this as a filter? I.e. as an addition to [this test](https://github.com/Polyconseil/easygettext/blob/master/src/extract.spec.js#L156):  
```
should extract filters with various patterns
```  
I tried it this way but got stuck because this doesn't really go well with the filters code:
```
'<h1 :label="$gettext(\'Pink Panther\')">';
```
Because it's not really a filter obviously. I guess.  
But I'm not sure where it makes most sense to try an implementation.  
Happy for any hints and pointers. Thx!
