### ISSUE TITLE
Add plain JavaScript support

### ISSUE THREAD

**Issue by peterthomashorn** [Polyconseil/easygettext#51]
I have a Vue component mixin in form of a plain _*.js_ file which includes translatable strings. By default it is ignored because it does not have the allowed file extension defined in [`src/extract-cli.js`](https://github.com/Polyconseil/easygettext/blob/master/src/extract-cli.js#L12).

To automatically execute string extraction I wrote a custom webpack plugin. That webpack plugin used to execute the command line script. To circumvent the limitation based on file extension I copied and adapted much of `extract-cli.js` and it works fine like this (partially renamed identifiers):

    if (ext === 'js') {
        const extractedStringsFromScript = javascriptExtraction.extractStringsFromJavascript(file, data);
        extractor.processStrings(extractedStringsFromScript);
    } else {
        extractor.parse(file, extraction.preprocessTemplate(data, ext));
        extractor.parseVueJavascript(file, extraction.preprocessScriptTags(data, ext));
    }

I just noticed that gettext annotations like comments and context are ignored in JavaScript and also seem not to be looked for anyway. That might be worth a different issue, if the feature request of plain JavaScript support is not declined.

**Comment by vperron** [comment]
I don't do feature requests as I don't personnally have the time to implement all those use cases !

But I usually merge the pull requests very quickly; if you're interested I'm all in for this plain JS support and the accompanying documentation (and you'd become a maintainer)

**Comment by peterthomashorn** [comment]
I will try to find some minutes within the next days to work up a pull request.

**Comment by vperron** [comment]
I will do that and also make you a contributor to this repository, so that you have more power to flex easygettext to your needs ! Do you have an NPM handle as well ?

**Comment by peterthomashorn** [comment]
Now I have, it is `~peterthomashorn`.

**Comment by vperron** [comment]
There you go ! Use a combination of `npm version patch` (bugfixes) or `npm version minor` (new features) then `npm version publish` to publish new versions. We don't maintain a changelog yet, even though that could be handy. I already published minutes ago a new minor with your changes. Thanks !
