### ISSUE TITLE
How to use gettext-extract?

### ISSUE THREAD

**Issue by pantuchy** [Polyconseil/easygettext#54]
Hello.
Could someone please explain, how to use tool "gettext-extract"? If I simply call "gettext-extract" with params in command line, it shows error, because does not know "gettext-extract" command. Should I install it globally or installing "npm install --dev easygettext" is enough?

Thank you.

**Comment by peterthomashorn** [comment]
If you have it installed as a development dependency in your project, you should be abled to execute:

    $ node_modules/.bin/gettext-extract

The command is not available in your global `$PATH` automatically.

**Comment by vperron** [comment]
Hello, this is true and you can also use `npx` to do that. Most npm-based CLI tools do work like this.
