### ISSUE TITLE
How to use with Pug for server-side localization?

### ISSUE THREAD

**Issue by pm5** [Polyconseil/easygettext#61]
I am using `gettext-extract` to extract tokens in Pug templates.  However, it seems Pug do not have a default way of doing l10n when it renders templates at the server-side.  I resort to use a simple `i18n` function with Pug's interpolation, so the text that needs to be translated looks like `#{i18n && i18n("Please translate this to your language.")}`.  The trouble is, now I cannot tweak `gettext-extract` to recognize these tokens.

Can someone with experiences in using this with Pug templates share how they did it?

**Comment by vperron** [comment]
I think you're taking the problem in the wrong way. You should put your token to be translated as a variable (as `{{ myTranslation }}`) and use Javascript to translate that (`const myTranslation = i18n('my text to translate')`) and use easygettext on your javascript file with the `i18n` token match.

**Comment by pm5** [comment]
Thanks for sharing.  This kind of makes sense, except that you were suggesting using easygettext on JavaScript files?  Haven't tried that before, actually.  The repo says easygettext is a "tokens extraction tools for HTML and Jade files", so I haven't thought of using it on JavaScript files.  Also, what then is the purpose of supporting Pug templates in easygettext?

Maybe I got the whole picture wrong somewhere.  Could you elaborate a bit more about the intended scheme of using easygettext?

**Comment by vperron** [comment]
You are right, the README is horribly outdated.

easygettext supports extracting tokens from Javascript / ES7+ / Vue files directly as well, I'll update that !!!
