### ISSUE TITLE
SyntaxError: Unexpected token when extracting .vue file with JSX expression

### ISSUE THREAD

**Issue by HaydnChen** [Polyconseil/easygettext#65]
VUE support JSX since 2.0, so gettext-extract should also recognize JSX such as
`render: (h, { row }) => {
            return (
              <div>
                ...
              </div>
            )
          }`

**Comment by vperron** [comment]
Yes it maybe should, and it could be the case if you open a tested pull request for this !!

Thanks for your interest !
