### ISSUE TITLE
Webpack require and translate tag

### ISSUE THREAD

**Issue by R-Kurbatovvakoms** [Polyconseil/easygettext#7]
Sorry to disturb, but npm still has easygettext v1.0.2 which fails on webpack's require in jade and doesn't recognize simple `translate` tag (PR for that exists but can't be merged).

I'd also liked to know how to extract files recursively. `./app/*.jade` extracts only ./app/index.jade and `./app/**/*.jade` extracts exactly all first-level files like ./app/aaa/bbb.jade, neither index nor more nested files.

**Comment by R-Kurbatovvakoms** [comment]
For latter question I think I can provide PR with glob usage if it is needed. All else, hope, is fixed in 1.0.3.

**Comment by raphael-boucher** [comment]
Version 1.0.3 is now available on npm, sorry for the inconvenience!
It works with webpack require and translate tag.

Contributions are always welcome!

**Comment by vperron** [comment]
About the second matter, what's the use case ? I was under the impression that easygettext should not bother too much with globs and just accept a list of files (which you got with a regular find, or any other filtering method) that you want to be parsed. Globbing in my opinion may not solve most problems :) What if you now need to analyze src/**/*.jade AND assets/**/*.html ?

For instance: `find src -name '*.jade' -o -name '*.html' | easygettext` is a powerful rationale in my opinion.

I stand for a KISS principle with easygettext, but depending on how you view things, that may change !

All the best,

**Comment by R-Kurbatovvakoms** [comment]
@raphael-boucher thanks!

@vperron thanks too, I'm just switching from gulp-based solution to webpack/pure npm so need to forget about bad habits. :) Simple find should really be enough.

**Comment by vperron** [comment]
Then, let's close this one, right ? ;)

**Comment by R-Kurbatovvakoms** [comment]
Sure.
