### ISSUE TITLE
Support optional chaining

### ISSUE THREAD

**Issue by sellittf** [Polyconseil/easygettext#84]
Running the extraction, I got the following error message:
`Trace: SyntaxError: Line xx, column xx: Unexpected token .`

This is caused by the optional chaining operator `?.` and it seems that at the moment the `gettext-extract` doesn't support it yet.

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Thanks for the great job!

**Comment by Knogobert** [comment]
This should be supported by #72 , that is merged and upcoming for release.

I myself can't wait to be able to use babel parser instead of acorn. As that would let us use babel plugins for parsing.

To use babel as parser, pass it along with the cli command like so: `gettext-extract --parser=babel <FILES>`

**Comment by Knogobert** [comment]
Can confirm now that I've been using optional-chaining and nullish-coalesce for months, that it works as expected. You just have to use babel as the parser. Closing this issue now.

**Comment by dschmidt** [comment]
For anyone who stumbles upon this: The fix only affects JavaScript - *not* TypeScript!

acorn and babel are afaict only used for javascript extraction, typescript uses buntis which is dead and doesn't support optional chaining, compare:

https://github.com/Polyconseil/easygettext/blob/6e3c24b3fdf0ae15447b58f9fd1d9910b222eee7/src/javascript-extract.js
https://github.com/Polyconseil/easygettext/blob/6e3c24b3fdf0ae15447b58f9fd1d9910b222eee7/src/typescript-extract.js

When I'm trying to extract from a .vue file using typescript the stacktrace directly points into buntis.
