### ISSUE TITLE
Feature request: use peer/optional dependencies to reduce node_modules

### ISSUE THREAD

**Issue by janlazo** [Polyconseil/easygettext#87]
I am using this package for translations in Javascript and Vue. I would like to avoid installing `pug` listed in https://github.com/Polyconseil/easygettext/blob/master/package.json. Likewise, if I am extracting translations from `pug` files only, then I would like to avoid installing `vue` packages.

I am mentioning `pug` here because I want to avoid installing its transitive dependencies, specifically https://github.com/fsevents/fsevents. `fsevents` is hard to upgrade because of other higher-level packages that depend on it but removing pug is one less linkage to deprecated versions of fsevents.

**Comment by vperron** [comment]
Would you be willing to submit a PR putting vue & pug dependencies as optional, and make the software raise a warning whenever they could not be installed ? cf https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by janlazo** [comment]
Yes.
