### ISSUE TITLE
2.14.0 stopped extracting strings from some Vue components

### ISSUE THREAD

**Issue by angelikatyborska** [Polyconseil/easygettext#93]
I'm using this project together with vue-gettext. I have Vue components in my project written in two different ways.

In `.vue` files like this:
```
<template>
  <h1 v-translate>Test String 1</h1>
</template>

<script>
export default {
  name: 'TestComponent1'
}
</script>
```

And in `.js` files written like this:
```js
import Vue from 'vue'

const TestComponent2 = Vue.component('TestComponent2', {
  template: `
    <h1 v-translate>Test String 2</h1>
  `
})

export default TestComponent2
```

I am trying to update from 2.13.0 to 2.14.0, but that causes the strings from Vue components written using the second style to be ignored.

I set up a repository that shows this. Take a look here: https://github.com/angelikatyborska/easygettext-2-14-0-bug/commits/master

First I set up everything using easygettext 2.13.0 (https://github.com/angelikatyborska/easygettext-2-14-0-bug/commit/fd64bde6818341637437322a3570cb99f9a72788) and running `gettext-extract` (see my `'gettext-extract'` script in `package.json` for details) extracts strings from both components like I want it to. Then, I updated to easygettext 2.14.0 (https://github.com/angelikatyborska/easygettext-2-14-0-bug/commit/f5c4e73378aacba32f7d1f195f839a72ea2eabf2) and running `gettext-extract` removed some of the strings.

**Comment by vperron** [comment]
Thanks for reporting this ! I'll try and take a look into it very soon. Maybe @Knogobert could also take a quick look ?

**Comment by torfeld6** [comment]
Hi @angelikatyborska 

Can you please confirm the PR #94 is resolving your issue?

Kind Regards
Joshua

**Comment by angelikatyborska** [comment]
@torfeld6 I tested with the current state of the master branch (https://github.com/Polyconseil/easygettext/commit/47e2464ff363f49d2bb3b35da1b95ca144db63dd) and this issue is resolved, but a new issue appeared. Strings added to my Vue components [this way](https://github.com/angelikatyborska/easygettext-2-14-0-bug/blob/67aa8bc74b743a836110010a776ab3b2f61f36fd/src/components/TestComponent1.vue#L12) now disappeared from the output. I added two more commits to my demo repo to show this (https://github.com/angelikatyborska/easygettext-2-14-0-bug/commit/67aa8bc74b743a836110010a776ab3b2f61f36fd, https://github.com/angelikatyborska/easygettext-2-14-0-bug/commit/90ff81a4c8aea21d74a50415968c0a1a1490a0b3).

**Comment by vperron** [comment]
Then I'll hold off the new easygettext release until @torfeld6 ou @angelikatyborska finds a solution :)

**Comment by torfeld6** [comment]
Hi @vperron. I'm not sure about this one. The extractor function `extract` is being used in all tests and in @angelikatyborska's case works. But `extract-cli.js` has kind of it's own `extract`-logic, which is not being tested and in this case doesn't call `parseJavascript` for `.vue` components.

The change was applied about 10 months ago: https://github.com/Polyconseil/easygettext/commit/b612f643b7a45f5dd5b9c69b1face0831973ea61#diff-d02db1886300be48b7371dc7819f1634R72

I replaced the extract-logic in `extract-cli.js` with the `extractor.extract` function and added the property `jsParser` to it. It appeared to be the only addition in the replaced logic. It works, but it is a major change.

Can you please have a look at it and let me know what you think about the following Pull-Request? And @angelikatyborska I'm sorry, but can I ask you to please test again if all your issues are resolved with the following Pull-Request?

https://github.com/Polyconseil/easygettext/pull/95

**Comment by angelikatyborska** [comment]
@torfeld6 When using easygettext from this commit https://github.com/PitcherAG/easygettext/commit/35fd455607845b3f1f5f1f5f1dd0a8e939568bb7, everything works as expected 👍

**Comment by vperron** [comment]
@angelikatyborska does the 2.15 version fix your issue ?

**Comment by angelikatyborska** [comment]
@vperron Yes! 2.15 behaves exactly the same as 2.13 with regard to string extraction from my Vue components. Thank you 🎉

**Comment by Knogobert** [comment]
Thank you for fixing this issue @torfeld6 !
